#!/usr/bin/env ruby

ENV['RAILS_ENV'] ||= 'development'
require ::File.expand_path('../../config/environment',  __FILE__)
require 'Monitor'

class CleanerDaemon < DaemonSpawn::Base
  def start(args)
    @continue = true
    count = 0
    lock = Monitor.new
    while @continue do
      if count < 16
        Thread.new do
          lock.synchronize{ count += 1 }
          begin Clean.perform end
          lock.synchronize{ count -= 1 }
        end
      end
      sleep(1)
    end
  end

  def stop
    @continue = false
  end
end

CleanerDaemon.spawn!({
  :processes => 1,
  :log_file => File.join(Rails.root, "log", "cleaner.log"),
  :pid_file => File.join(Rails.root, 'tmp', 'pids', 'cleaner.pid'),
  :sync_log => true,
  :working_dir => Rails.root,
  :singleton => true
})
