#!/usr/bin/env ruby

ENV['RAILS_ENV'] ||= 'development'
require ::File.expand_path('../../config/environment',  __FILE__)

class TweetBotDaemon < DaemonSpawn::Base
  def start(args)
    @worker = Resque::Worker.new("tweet_bot")
    @worker.verbose = true
    @worker.work(1)
  end

  def stop
    @worker.try(:shutdown)
  end
end

TweetBotDaemon.spawn!({
  :processes => 1,
  :log_file => File.join(Rails.root, "log", "tweet_bot.log"),
  :pid_file => File.join(Rails.root, 'tmp', 'pids', 'tweet_bot.pid'),
  :sync_log => true,
  :working_dir => Rails.root,
  :singleton => true
})
