#!/usr/bin/env ruby

ENV['RAILS_ENV'] ||= 'development'
require ::File.expand_path('../../config/environment',  __FILE__)

class CleanerDaemon < DaemonSpawn::Base
  def start(args)
    @continue = true
    while @continue do
      begin Clean.perform end
      sleep(5)
    end
  end

  def stop
    @continue = false
  end
end

CleanerDaemon.spawn!({
  :processes => 1,
  :log_file => File.join(Rails.root, "log", "cleaner.log"),
  :pid_file => File.join(Rails.root, 'tmp', 'pids', 'cleaner.pid'),
  :sync_log => true,
  :working_dir => Rails.root,
  :singleton => true
})
