#!/usr/bin/env ruby

ENV['RAILS_ENV'] ||= 'development'
require ::File.expand_path('../../config/environment',  __FILE__)

class CleanerDaemon < DaemonSpawn::Base
  def start(args)
    @pid = Process.spawn("bundle exec resque-pool --environment #{Rails.env}")
    while true do
      Resque.enqueue(Clean) if Resque.size('cleaner') <= 5
      Resque.enqueue(CleanThemAll) if Resque.size('clean_them_all') <= 1
      sleep(1)
    end
  end

  def stop
    Process.kill('SIGTERM', @pid)
  end
end

CleanerDaemon.spawn!({
  :processes => 1,
  :log_file => File.join(Rails.root, "log", "cleaner.log"),
  :pid_file => File.join(Rails.root, 'tmp', 'pids', 'cleaner.pid'),
  :sync_log => true,
  :working_dir => Rails.root,
  :singleton => true
})
