#!/bin/sh
#
# chkconfig: 2345 55 25

set -e

# Feel free to change any of the following variables for your app:
APP_ROOT=/var/www/app/kurorekishi/current
ENVIRONMENT=production
USER=app
action="$1"
set -u

cd $APP_ROOT || exit 1

sig () {
  test -s "$PID" && kill -$1 `cat $PID`
}

case $action in
start)
  CMD="cd $APP_ROOT; RAILS_ENV=$ENVIRONMENT bundle exec script/resque_cleaner start"
  su - $USER -c "$CMD"
  ;;
stop)
  CMD="cd $APP_ROOT; RAILS_ENV=$ENVIRONMENT bundle exec script/resque_cleaner stop"
  su - $USER -c "$CMD"
  ;;
esac
